### PR TITLE
update recipes

### PR DESCRIPTION
**Pull request by ocefpaf**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by ocefpaf** [comment]
@isuruf do you have an idea of what is going on here?

```
checking whether the C++ compiler works... no
configure: error: in `/home/conda/feedstock_root/build_artifacts/libdap4_1533923153126/work':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
```

I checked the `config.log` but I could not see anything obviously wrong there.

**Comment by isuruf** [comment]
Can you post the config.log?

**Comment by ocefpaf** [comment]
> Can you post the config.log?

Sure! Thanks for looking at it:

https://gist.github.com/ocefpaf/41dbed5273940e13154a7a33277444e0

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@conda-forge-admin, please lint

**Comment by ocefpaf** [comment]
I could advance a little bit by pinning `bison` to `3.0.4`. But No idea of what is going on OS X and Linux seems to be confused when trying to find `flex` headers, which is properly installed :-(

**Pull request closed without merging**
