### PR TITLE
Try make check on OS X

### LINKED ISSUE #1: Issue on os x
There seems to be an issue with the OS X build. I first thought there was an issue with some test setup, but it seems to be the build itself.

I'm trying to solve this with the developers, ref OPENDAP/libdap4#20

Testing the build here
https://travis-ci.org/nansencenter/libdap4-feedstock

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #1

Ping @aleksandervines this may work...

### CODE REVIEW

**Comment by aleksandervines** [comment]
Failed :/ Though this was much more promising! instead of 37/40 failed tests, it failed on 4/224

**Comment by ocefpaf** [comment]
Most of the other failures was b/c conda could not find those libs at test-time. So that is fixed. The remaining errors now are "real" errors that we need to address though.

**Comment by ocefpaf** [comment]
I don't know the first thing about theses tests, so it may be worth reporting them upstream to get some advice.

```
177: trans test_array_5.xml scale(a,0.001)  test_array_5.xml.1.func_base FAILED (DMRTest.at:483)
178: trans test_array_5.xml scale(b,0.001)  test_array_5.xml.2.func_base FAILED (DMRTest.at:484)
179: trans test_array_5.xml scale(c,0.001)  test_array_5.xml.3.func_base FAILED (DMRTest.at:486)
180: trans test_array_5.xml scale(d,0.001)  test_array_5.xml.4.func_base FAILED (DMRTest.at:487)
```

**Comment by aleksandervines** [comment]
Yes. It failed exactly the same on my mac now, so I got some log files to work with, though I can't get anything useful out of those I think. I will report the issue upstream.

**Pull request closed without merging**
