### PR TITLE
Use system libuuid instead of portable copy

### PR DESCRIPTION
**Pull request by ceholden**
Ping @ocefpaf -- you mentioned helping out with the `libuuid` issue and I'd love the help here.

Portable copy prevents [Qt from compiling](https://github.com/conda-forge/qt-feedstock/pull/9), but not having `libuuid` in Qt causes linking errors when linux-utils (system) libuuid clashes with portable copy, preventing compiling and running of things like QGIS that combine Qt + GDAL. As far as I can tell, this is 1 of 3 libraries that use `libuuid` and is the only one in the GDAL stack.

For instance, using the new Qt `4.8.7-3` that does not compile with `libuuid-feedstock`, I see:

``` bash
> qgis                           
qgis: /home/ceholden/conda/envs/agdc-py2/bin/../lib/./libuuid.so.1: no version information available (required by /usr/lib/libSM.so.6)
Warning: loading of qgis translation failed [/home/ceholden/conda/envs/agdc-py2/share/qgis/i18n//qgis_en_US]
Warning: loading of qt translation failed [/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho/translations/qt_en_US]
[1]    1768 segmentation fault (core dumped)  qgis
```

This is the same issue I was seeing before `libuuid` was put into the Qt recipe (see [libuuid issue](https://github.com/conda-forge/libuuid-feedstock/issues/8)).

As a first proof of correctness, it looks like either copy -- the "portable" from the `libuuid-feedstock` or the "system" from apt/yum/etc. -- works. The developers use Ubuntu's `uuid-dev` in their testing ([travis.yml](https://github.com/OPENDAP/libdap4/blob/master/.travis.yml#L49)).

Second step -- ensuring this external dependency isn't onerous -- is somewhat harder. As a starting point, the `xenial` Docker image has a copy of the library (`/lib/x86_64-linux-gnu/libuuid.so.1.3.0`). Compiling this build without `libuuid-devel` only seemed to be missing the header files. All of my personal machines and computing cluster machines have this library, and `libuuid-devel` has quite a few reverse dependencies. Not sure how to fully address this but I'd appreciate any feedback or suggestions.

### CODE REVIEW

**Comment by ceholden** [comment]
Did some more digging:

First, the `condaforge/linux-anvil` Docker image already has `libuuid` installed so the difficulties experienced when developing this feedstock likely could have been solved by installing the headers (`libuuid-devel`) instead of the "portable" copy from the feedstock.

The `libuuid` RPM package is pulled in through a dependency of `libSM-devel` (and maybe others) as: `libSM-devel` -> `libSM` -> `libuuid`. Taken from a Bash session in the `linux-anvil` Docker image:

``` bash
(root) [root@7a1d4c9089ee /]# yum deplist libSM.x86_64
...
package: libSM.x86_64 1.2.1-2.el6
  dependency: libuuid.so.1()(64bit)
   provider: libuuid.x86_64 2.17.2-12.24.el6
```

Second, while I haven't tracked down where and exactly why adding `libuuid.so` from `libuuid-feedstock` prevents Qt from compiling (and I hope to avoid doing so since it's such a beast), the Session Manager (`libSM.so`) added in the PR that broke Qt's compatibility in QGIS for me links against the system `libuuid.so`. My guess is the same conflict I see in linking QGIS happened when linking Qt (i.e., linking against libraries that use two separate sources of `libuuid.so`).

``` bash
(root) [root@7a1d4c9089ee /]# ldd /usr/lib64/libSM.so
...
    libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f6d8bd48000)
...
```

**Comment by aleksandervines** [comment]
On this PR you removed libuuid from build requirement, but not from run requirement? As far as I understand, this will cause issues :)

**Comment by ocefpaf** [comment]
@ceholden apologies for not being so activity here. (Day job is demanding more attention lately :smile:)

To be honest I haven't looked at the problem yet but I understand that we have a few workarounds at the moment.
1. Do not compile `gdal` with `libdap4`
2. Do not compiled `libdap4` with `libuuid` altogether
3. Use system `libuuid` for `libdap4` (this PR)

@aleksandervines What do you think about `2` and `3`? If those are not OK I can bump `gdal` and produce a version with `libdap4` until we figure this out.

**Comment by aleksandervines** [comment]
Is 2 an option? If so, go for it! :D (I was under the impression that uuid.h was a requirement for libdap4 - ref OPENDAP/libdap4#20 ) 

System libuuid: isn't versioning issues an issue then? I don't know how stable/backwards compatible libuuid is?

1 is not really an option for us :/

**Comment by ocefpaf** [comment]
> Is 2 an option? If so, go for it! :D (I was under the impression that uuid.h was a requirement for libdap4 - ref OPENDAP/libdap4#20 ) 

I thought it could be option dep. But it does no seem to be the case. So that one is out.

> 1 is not really an option for us :/

This one is also out then.

> System libuuid: isn't versioning issues an issue then? I don't know how stable/backwards compatible libuuid is?

We can only experiment and hope for the best. Ideally we should avoid that and use only `conda-forge`'s `libuuid` everywhere to ensure we have a consistent version but I do not have the time to dig into this right now :unamused:

**Comment by aleksandervines** [comment]
Lets experiment then.

**Comment by ocefpaf** [comment]
> Lets experiment then.

:+1: 

> On this PR you removed libuuid from build requirement, but not from run requirement? As far as I understand, this will cause issues :)

@ceholden can you address this so we can move the experimentation forward?

**Comment by ceholden** [comment]
> On this PR you removed libuuid from build requirement, but not from run requirement? As far as I understand, this will cause issues :)

Whoops -- thanks for catching this!

I think option 3 is the path forward -- keep libdap4 in GDAL and use a consistent libuuid. Hoping it works out!

**Comment by ocefpaf** [comment]
If this does not work we will revert it later. Let's try it now... (We may need to bump `gdal` too.)

**Comment by ceholden** [comment]
Good news! I built QGIS locally using the new `libdap4` inside the `condaforge/linux-anvil` Docker image -- it passed its tests and runs just like before now that the `libuuid` ducks are in a row. Looks like we don't need to bump GDAL but just bump QGIS.

Thank you @aleksandervines and @ocefpaf for your attention. I seem to be able to initialize GDAL drivers that depend on `libdap4` without issue, but I'm hoping the change to this feedstock isn't negatively affecting anything I haven't seen.

**Comment by ocefpaf** [comment]
Awesome. Let me know if you uncover anything in your tests. I will preform some gdal tests soon.

@aleksandervines maybe we should add an specific `libdap4` test to the `gdal` feedstocks. Let me know if you have any idea of a simple 1-liner we can run there.

**Comment by aleksandervines** [comment]
@ocefpaf 
This is a 1-liner that provides a very simple test to check dap support:
gdalinfo http://thredds.nersc.no/thredds/dodsC/greenpath/Model/topaz

**Comment by ocefpaf** [comment]
Awesome! Thanks @aleksandervines!! I am adding this to the `gdal` feedstock soon.

**Pull request merged**
